### ISSUE TITLE
Hardcoded Oauth client/secret for google?

### ISSUE THREAD

**Issue by jhohertz** [appscode/guard#138]
I was trying to something along the lines of #134, having setup guard for API control, and looking at oauth2 proxy for dashboard. I got the latter setup and realised this was authenticating from a different "client" than the API, and as such the bearer token wasn't being recognised.

Knowing guard works exclusively off the service account JSON for secrets, I went looking at the code to see how it creates a client secret from this, and was surprised to find a set of credentials hard-coded as constants in the google auth provider.

Am I missing something here, or is everyone using this auth provider making use of someone else's Oauth2 client details? (With the JSON only being used for the group API lookup)

https://github.com/appscode/guard/blob/0fd69458e855fa3cc590432acbdc310bde1a1708/auth/providers/google/google.go#L14-L21

**Comment by tamalsaha** [comment]
@diptadas probably related to what you are doing now.

**Comment by tamalsaha** [comment]
@jhohertz, happy to explain the process.

> Knowing guard works exclusively off the service account JSON for secrets, I went looking at the code to see how it creates a client secret from this, and was surprised to find a set of credentials hard-coded as constants in the google auth provider.

"Knowing guard works exclusively off the service account JSON for secrets," is not correct. The user authorization is done by verifying the user's id-token. client secrets you mentioned not used to get Google user's group information. The service account json provided to installer is used to create a client and call Google Directory SDK . See here: https://github.com/appscode/guard/blob/master/auth/providers/google/google.go#L57 . This service account has to be authorized by the G-Suite domain admin beforehand. https://github.com/appscode/guard/blob/master/docs/guides/authenticator/google.md#create-the-service-account-and-its-credentials

> Am I missing something here, or is everyone using this auth provider making use of someone else's Oauth2 client details?

There are 2 clients involved here.

- The service account provided by the user's G-Suite account: This is used on the server side to call Google Directory api.

- The hard-coded oauth client. This is a "OAuth 2.0 for Mobile & Desktop Apps" as described here: https://developers.google.com/identity/protocols/OAuth2InstalledApp

To use Google auth provider, first every user have to run the command:
```
guard get token -o google
```
This will start a oauth prompt. This requires a oauth client that is hard-coded in the code. Since this is a Oauth for Desktop application, it is ok to publish the client secret and additional permission can't be grant after initial grant. How do you know so? This client secret can only use localhost as callback URL. Web oauth clients are not allowed to use localhost address. See here:

![google-oauth-desktop](https://user-images.githubusercontent.com/94814/41046828-fb67ae5e-695f-11e8-8dda-e900d6bb2291.png)

After user permits, guard completed the auth code exchange and updates the ~/.kube/config file as below:

```
- name: tamal@appscode.com
  user:
    auth-provider:
      config:
        client-id: 37154062056-220683ek37naab43v23vc5qg01k1j14g.apps.googleusercontent.com
        client-secret: pB9ITCuMPLj-bkObrTqKbt57
        id-token: xxxxxxxxxxxHzQ
        idp-issuer-url: https://accounts.google.com
        refresh-token: xxxxxxxxxxxxxxxxxxxxxxx
      name: oidc
```

Now, when user calls `kubectl get pods`, kubectl will get send the id-token as bearer token to kube-apiserver. Because we are using `oidc` provider. Then kube-apiserver will send this id-token to Guard server which guard server will first verify cryptographically. https://github.com/appscode/guard/blob/master/auth/providers/google/google.go#L73

After verification, if we find that the email address associated with this id-toekn is from the G-guide domain, then we make Google directory api call using the step 1.
https://github.com/appscode/guard/blob/master/auth/providers/google/google.go#L85

So, this hard-coded client is never used on Guard server. It is only used to get user's id-token on local machine.

Sorry it took me some time to answer. Let me know if there are any further question.

**Comment by jhohertz** [comment]
Thank you for the detailed response. 

To be clear I had this working already, and by stating that it was "working only with the JSON file", that was simply to say that is the only secret data that was configured in guard. Which is why I was surprised to see the second set of hard-coded credentials in the client.

The core of my concern, using an API token/secret, that is not under our control just wasn't acceptable for us, not even from an insecurity perspective, but from a service continuity one. (IE: what if the secret is de-provisioned at some point in the future, for... whatever reason).

We've settled on an alternative implementation that satisfies this for us, so I will close this off for now.

Thanks again.

**Comment by tamalsaha** [comment]
Thanks @jhohertz , we could probably just add the instructions on how to set up the oauth account on your own account. How are you setting this up now, may I ask?
